### ISSUE TITLE
Don't work on wordpress

### ISSUE THREAD

**Issue by Irina-kh** [padams/Open-Web-Analytics#143]
OWA installed like a plugin wordpress. But when i try to go to page Reporting or Administration from dashboard, i have this:
Your Account lacks the necessary priviledges to access the requested resource.
I am admin in wordpress. Where can be mistake?

**Comment by sudojudo** [comment]
Keep in mind that the WP plugin is a separate from OWA, and if you're having issues with it, contact its creator via WP.

That said, I've seen the error you mention, and it can be bypassed by directly accessing the plugin from the left column, instead of through the general plugin menu.

If you've tried that, and still have the error, check your permissions.  Honestly, it's much easier to just manually add the OWA code than it is to deal with the WP plugin.  Just add the JavaScript to your WP footer and be done with it.

**Comment by Chnutz** [comment]
WP-Plugin don't work for mee, too. 
"Fatal Error" when I try to activate it.
The footer.php is correct, WP-Cache-plugin not installed.

Additionally the link to the WP-developer and the WP-developer page leads to a 1.pixel-png :-(

Any idea?
Thanks and Greetings
Chnutz

Is this project stopped?!

**Comment by swapniljaykar** [comment]
I had implemented the OWA code on WordPress site in footer section before the closing of the body tag. Even there is no data collected.

Any suggestion?

**Comment by padams** [comment]
This is fixed in master.
