### ISSUE TITLE
[Feature suggestion] Tracking pageview by image

### ISSUE THREAD

**Issue by joubertredrat** [padams/Open-Web-Analytics#157]
Hi guys,

Today OWA have track only by js or php, but I think that is good idea to have option to track by image tag too, what you think?

Thanks.

**Comment by padams** [comment]
That's what the JS tracker does.

It creates an IMG tag with the appropriate GET request params.

**Comment by joubertredrat** [comment]
hi @padams 

Then I can make this as example?
```html
<img src="https://owa.my.domain/owa_php.php?setSiteId=abcdef&trackPageView=1"/>
```

**Comment by padams** [comment]
No. The JS tracker has to create the image tag dynamically in order to pass  all of the tracking params into the GET request.

If you just used a static image tag like you are  suggesting then how would you tell OWA things such as the website that referred you to the page to begin with or page level meta data such as title or page type etc. ?

I suppose there are some applications for a more simplified fracker that just reports page views and  sessions by URL - which is about all you could hope to get out of the static IMG tag approach.
