### ISSUE TITLE
Country not set

### ISSUE THREAD

**Issue by binky33** [padams/Open-Web-Analytics#169]
Hi
Is there a setting I am missing because I can't get the country info on the reports it just says not set!
TIA
Binky

BTW I am not a programmer so anything too technical will be difficult

**Comment by SgtBurned** [comment]
You need to download a geoIP database. Set it in the config file;

Download: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip

go to your OWA Folder -> owa-config.php

and add this line;

define('OWA_MAXMIND_DATA_DIR', 'wherever/your/owa-data/folder/is/owa-data/');	// Maxmind GeoLite City GEOLOCATION path


That is where your GeoLiteCity.dat database will be. Once you have this, it will locate all IP's to a city.

**Comment by binky33** [comment]
Thanks for info but I don't seem to have got it right

**Comment by binky33** [comment]
Tried again but still not managed it............. I must be more stupid than I thought

**Comment by doom99** [comment]
I have same issue - no country or city data is being logged.  I have verified that the free geoip data is in place in the correct location.  I have tried with 1.5.4 as well as master.

**Comment by skinhat** [comment]
SgtBurned gave the wrong URL for the database. It should be
http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

Its expecting an mmdb database not a CSV file.

> You need to download a geoIP database. Set it in the config file;
> 
> Download: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip

**Comment by SgtBurned** [comment]
Ahh sorry about that, must have copied the wrong link from their site.

**Comment by ThePrudentNinja** [comment]
Different person, same problem. Instead of creating a new ticket, just replying to this one.

What I've done so far:
* Downloaded http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz and put it under owa-data directory. Then tried it under owa-data/maxmind/. Then tried editing the owa-config.php to point to the directory of the database as said in this thread.
* Tried the instructions on the wiki page exactly as specified.

Results: Geolocation still doesn't work.

Is there anything else to try? Maybe the wiki page could be updated?

**Comment by gardner** [comment]
In case anyone else runs into this issue. My version of OWA was looking for a `.dat` file which I found on MaxMind's legacy page: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

I put that file in a folder that I created at `/owa/owa-data/maxmind` and decompressed it with the command `gzip -d GeoLiteCity.dat.gz`

It looks like newer code from the master branch looks for the newer mmdb formatted file [here](https://github.com/padams/Open-Web-Analytics/blob/020dc5984370c7a67a4a85a9042369b20bfe8cba/modules/maxmind_geoip/classes/maxmind.php#L56)

**Comment by PliSsK** [comment]
Is anyone using OWA 1.6.0? I can't seem to get it to work. I followed the instructions on the Maxmind GitHub page as best I could.

https://github.com/padams/Open-Web-Analytics/wiki/Maxmind-GeoIP-Module

I put the 'GeoIP.dat' file (country geo-location) inside the stats/owa-data/maxmind/ folder that I created. I updated the owa-config.php file to include the line:

<addr>define('OWA_MAXMIND_DATA_DIR', 'owa-data/maxmind/'); // Maxmind GeoIP.dat GEOLOCATION path</addr>

I also tried it using:

<addr>define('OWA_MAXMIND_DATA_DIR', 'owa-data/maxmind/GeoIP.dat'); // Maxmind GeoIP.dat GEOLOCATION path</addr>

**Comment by dac2020** [comment]
I've had #177 open since last June and still cannot find a solution to any of these 'not set' problems.

**Comment by chywUa** [comment]
1.Copy file GeoLite2-City.mmdb in directory owa-data
2. Include the line in owa-config.php:
define ('OWA_MAXMIND_DATA_DIR', 'owa-data/'); // Maxmind GeoIP.dat GEOLOCATION path
3. updated tracking tag site 
OK!

**Comment by dac2020** [comment]
This is a really old issue, a problem I had commented about also.
Which version/s would this be for and is this fixed in a newer version and if so, which?

**Comment by doom99** [comment]
Hi   sorry but I moved on from OWA a year or more ago really don't recall
the details

On Mar 22, 2018 10:55 AM, "mike" <notifications@github.com> wrote:

This is a really old issue, a problem I had commented about also.
Which version/s would this be for and is this fixed in a newer version and
if so, which?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/padams/Open-Web-Analytics/issues/169#issuecomment-375335660>,
or mute the thread

**Comment by chywUa** [comment]
I installed a version 1.6.1  for testing today. 
There was such a problem, but it was decided by the algorithm that I described above.

**Comment by c-orazio** [comment]
Hum struggling a bit with this issue.
Is there still a free updated version of the geolitecity file?
It seems that we have to pay for all now?

**Comment by padams** [comment]
https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en
