### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by GoaPhuDen** [padams/Open-Web-Analytics#171]
Hi all,
I am trying to Add a New Tracked Site Profile on OWA.
But OWA don't show anything... :(
404 Not found...
This is screenshot : http://2.pik.vn/2016b3af25b9-2184-4e01-92a0-05a53bb9505c.png

any ideas ?

**Comment by GoaPhuDen** [comment]
any ideas ?

**Comment by colleenh218** [comment]
My sites appear that way, too, and nothing is being tracked. I'm wondering if anyone actually replies to issues on this site - I see a lot with no replies!

**Comment by Adventure30** [comment]
@colleenh218 Did you ever resolve your issues with OWA installation?  I just came across this application today and installed onto a Ubuntu server.  I may be experiencing the same issue you had.

I started searching online for effective OWA documentation and help with this issue.  Not finding much on OWA or the issue.  I may invest time and reverse engineer this system.  Still interested or deploying this system?  I am open to collaboration work.

**Comment by Adventure30** [comment]
Hello,

Thank you for your reply.

As I conducted searches on the Internet for infomration on this open source project, I noted there may be one guy trying to develop and support th open source project; Open, Web Analytics.

I did find another simular type of application available with a much more professional pollished look.  In a breif comparison, I noted one feature of the OWA system, offering a task very adventagous to website and webpage design; relating to presentation and marketing.

I intended to research further into the system layout and code of this Open, Web Analytics as a side project.  I am interested in the one key feature.  I specialize in computing science R&D, and striving for optimzation of the technology.

As a open source project, I do not think there is a company behind the project or web site.  This is what I find most intersting; as a potential business model to fork off the project and develop a major revunue generator web application service; hence my interest in collabrative development.

I have been working with Windows DOS, and their various desktop computing environments since 1981.   I have been a Microsoft technology provider partner since the 1990s.  Migrating one Windows Server to Server 2012 is a challenge…. I can imagine your stressful task load.

FYI - I build commercial Enterprise and Internet rack servers (all type form factors) for OEM Windows Servers, FreeBSD, Ubuntu, and others, Installations (data servers, clusters, data centers, cluster web servers, NAS, pfSense perimeter firewalls, clouds…).

I utilize the same OEM manufactures as selected by Facebook and Google for their in-house servers.  I am based in the Greater Metro Milwaukee area.

If interested please feel free to contact me.

Gene



====================================
NOTICE: The foregoing message contains confidential information (including attachments) intended only for the use of the addressee(s) named above. If you are not the addressee, or the person responsible for delivering it to the addressee, you are hereby notified, reading, disseminating, distributing, printing, or copying this message is strictly prohibited. If you have received this message in error, please notify us by replying to the message immediately.  Also, please proceed to erase the original message directly following your reply. Thank you.
====================================

**Comment by padams** [comment]
It's impossible to troubleshoot an issue like this without seeing the http requests that the browser is making as well as the OWA error logs showing how those requests are received by the server. If you re-post relevant details from both those then it's possible that someone could help point you in the right direction.

**Comment by padams** [comment]
Also, Windows is not a supposed OWA platform.
