### ISSUE TITLE
OWA installed on wordpress as directed but not working

### ISSUE THREAD

**Issue by zibzoob** [padams/Open-Web-Analytics#190]
Hello
I have a wordpress site on godaddy, I downloaded OWA 1.6, unzipped it and uploaded it using fileZila to the worpress folder and then activated it. but when I go to OWA admin page and click on the left side menu links like "Reporting" or "Administration" I get "Sorry, you are not allowed to access this page."

What is wrong? I made sure file permissions are correct but still get the same message 
I deactivate and reactivate again but no change

I appreciate your help

Thank you

**Comment by mr-moleman** [comment]
This is probably because your plugin directory name is wrong. For some reason the standard wordpress plugin install does not follow the installation instructions laid out in the wiki:
https://github.com/padams/Open-Web-Analytics/wiki/Installation
**NOTE: the folder must be named 'owa' (without the quotes) to work.**
