### ISSUE TITLE
Question: Is it possible to integrate log files and OWA?

### ISSUE THREAD

**Issue by coofercat** [padams/Open-Web-Analytics#191]
[This is a question, rather than an issue - links to forums and whatnot seem to lead here, so I'm sorry if this isn't the right place for this sort of thing]

I'm wondering if I could integrate log files with OWA. I'm wondering if I could write a 'log file tailer' process that would effectively do a 'tail -f' of my nginx access.log file. Every suitable line would then cause the tailer to send an event into OWA.

What I couldn't figure out is if there's a way to craft an event to post into OWA that contains all the details of the original page view. I guess what I'd like to do is to post data something like this:

```
{
  'timestamp': 12345678,
  'ip': '192.168.1.201',
  'url': '/some_page.html',
  'domain': 'www.example.com',
  'source': 'web01.example.com',
  'referrer': 'http://www.example.com/other_page.html',
  'response_code': 200,
}
```

Note that I of course need to tell OWA what IP address (and timestamp, etc) the event relates to, rather than letting OWA figure it out from the connection to to it. Is something like this possible?

**Comment by padams** [comment]
OWA has this built in. You can set up events to be queued to a log file for processing at set intervals using the CLI.

https://github.com/padams/Open-Web-Analytics/wiki/event-queueing

One could hack things so that GET requests to log.php simply write to nginx/apache logs, but you’d then be missing out on the environmental vars that PHP adds at the server level for each request.
