### ISSUE TITLE
Accidentally installed OWA onto my homepage, how to remove so people can view my website?

### ISSUE THREAD

**Issue by Nickzeb** [padams/Open-Web-Analytics#250]
Hello all, I'm very new to all of this.

I accidentally installed OWA using 123-reg.co.uk onto my domain homepage, thus when anyone tries to access my site the OWA login page is displayed and not my actual website content. I'm using 123-reg.co.uk to host my site, how do I completely remove OWA?

Thanks for any help, I've searched everywhere and am at a real road block. 

Nick

**Comment by cubetronic** [comment]
I'm just trying out OWA, but...

It sounds to me like you placed the _**contents**_ of the OWA folder (i.e. Open-Web-Analytics-1.6.0, or "owa" if you renamed it) into your web server's root directory (the main, lowest level directory). The proper way to install OWA is to place the OWA _**folder**_ into your web server's root directory. That way it won't conflict with your website.

```
/index.php             <--- this will be your website's homepage
/owa/index.php         <--- this is where the the OWA page should be
```
It sounds like you've over-written your website's index.php file with the OWA index.php file. Hopefully you have a backup of the index.php file you would like to use. You may also have over-written some other files with common names, like action.php.

So all you have to do is delete all the OWA files and folders from your server's root directory. In version 1.6.0 there are 5 folders and 39 files. I would look at a fresh download of the contents of Open-Web-Analytics-1.6.0 (or whatever version you tried to install), so that you know which files and folders to delete. Most of the files start with "owa_", which should make things easier.

That would uninstall OWA from the website, but then you need to make sure your site has the index.php you want, and any other files. If it's a WordPress site, for example, then then you could get a fresh download of the WordPress version you're using, and look at the contents of that folder (its root directory), and move any missing files into your websites root directory. I know in the case of WordPress that the index.php file is very generic and can easily be replaced.

For a full uninstall, you would also have to remove the SQL database you created for OWA, and anything else. You would know if you created a database, as it's not automatic.
