### ISSUE TITLE
Windows Installation Made Easy

### ISSUE THREAD

**Issue by Phoenix90210** [padams/Open-Web-Analytics#262]
I have recently installed OWA and found a rather easy way to do it for windows.

https://www.microsoft.com/web/downloads/platform.aspx

The Microsoft Web Platform Tool contains all 3 requirements you will need for OWA and OWA itself.
Its (almost) as simple as selecting PHP, MYSQL and OpenWebAnalytics from the tool and letting it do the base setup and install for you.

As per normal you will still need to change some settings depending on your infrastructure and environment post install to get everything working.

Adding the *.tpl extension as a MIME Type in IIS is a must as well.

**Comment by DJayJelks** [comment]
Hey Phoenix90210,

I hope you are still around. I was interested in your post due to me wanting to use Open Web Analytics to check Websites as I redevelop them. I like this open source analytics program, but I'm bit confused on what to start first after downloading the necessary files/programs.

Hope to hear from you. Thanks.

**Comment by Phoenix90210** [comment]
Hi Djay

Once you've downloaded the Micorsoft client and installed PHP, MYSQL and OpenWebAnalytics you will need to set up IIS first on the server and register the *.tpl extension as a MIME Type.

You will need to set up email forwarding in the OpenWebAnalytics config files to allow user access.

Basically once you've got it all installed and start IIS you should be half way there. Then you just need to follow the normal configuration instructions.

How far have you gotten with this?
