### ISSUE TITLE
404 after install

### ISSUE THREAD

**Issue by SlidingHorn** [padams/Open-Web-Analytics#311]
I installed my OWA, but when I go to "Login and generate a site tracker" I get a 404 error.

I do have this installed in a subdirectory that may have had mod_rewrite enabled at the time.  I've created an .htaccess file with "rewriteengine Off" and restarted apache, however, clicking the Login button still 404s.

**Comment by SlidingHorn** [comment]
I believe this is not an issue.  I just navigated to the domain.org/owa/index.php and was able to log in.  Issue closed!

**Comment by JialuZhang** [comment]
@SlidingHorn 
In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
