### ISSUE TITLE
Database Schema Installation failed. Please check the error log file for more details.

### ISSUE THREAD

**Issue by DeeeeLAN** [padams/Open-Web-Analytics#376]
I get this error when I am on the page to enter the domain and my email and password. I click continue, it gives me that error, but no log is produced. I set both settings in the config, but still, nothing.

Any ideas?

**Comment by bram1028** [comment]
Tried to install this today, and ran into this problem as well. This is the error (using `master`):

```
[07-Dec-2018 22:05:35 America/New_York] PHP Warning:  mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /REDACTED/plugins/db/owa_db_mysql.php on line 220
```

**Comment by DeeeeLAN** [comment]
Digging deeper, it looks like one of the tables fails to get created. For me, it was the user table.

**Comment by DeeeeLAN** [comment]
success! The user table has duplicate attributes for the ID field, SERIAL and AUTO_INCREMENT. SERIAL is an alias that includes AUTO_INCREMENT, and the duplication is causing the table creation to fail. I will file a pull request with the AUTO_INCREMENT field removed.

**Comment by DeeeeLAN** [comment]
Fixed in #377.

**Comment by bram1028** [comment]
That worked, thank you!

**Comment by padams** [comment]
Sounds like an issue with connecting to the DB.

**Comment by padams** [comment]
Awesome. I will merge.

**Comment by petrk94** [comment]
Facing same issue, why not bug fix release is available? Thats unbelievable, that since 1 year the issue is known and still there is no bug fix update available?

**Comment by bernd-wechner** [comment]
> Facing same issue, why not bug fix release is available? Thats unbelievable, that since 1 year the issue is known and still there is no bug fix update available?

Dude, it's FOSS.  "Unbelievable" is a term you have call on if you paid for some software  and don't feel you've got your money's worth. 

IN the mean time read up on developer burnout:

https://www.vice.com/en_us/article/43zak3/the-internet-was-built-on-the-free-labor-of-open-source-developers-is-that-sustainable

https://medium.com/hackernoon/why-theres-so-much-burnout-in-software-and-what-to-do-about-it-4ef0297ca7cc

then check the trail of clues, and you'll see:

1.  DeeeeLAN fixed it in December 2018.
2. padams  merged it into master in August 2019
3. Last web release was built July 2018

Given it's totally free, and open source you have these options:

1. Wait till the download at http://www.openwebanalytics.com/ is updated
2. Clone the git repo and implement it from master yourself. 

I know it's not ideal, and I share the frustration you seem to have (only I feel it with lots of FOSS). The problem remains that FOSS is often being maintained by volunteers who time and again move on in life and leave erstwhile projects stranded because the criticisms and expectations start to outweigh the returns they get from it (using it themselves, praise and encouragement etc.).

So in the world of FOSS< I suggest tread lightly and speak politely without demands.

**Comment by petrk94** [comment]
I know that issue.
As I'm even a developer and made open source projects (of course smaller ones). I'm not expecting anything big, just that the software is usable. A bug which make it unusable, make it not longer worth to share it with other people, that's the problem. How can I tell people to use OWA, If even the installation is failing?
Is there at least a workaround to solve this? Or what line I have to correct, than I kindly will make a pull request to make usable. I downloaded the website version, branches on GitHub are mostly dev only and not for usage in production made, so I don't tried the gut clone repo.
