### ISSUE TITLE
혹시 1.6.2 버전의 작은 Bug는 아닌지요 ??

### ISSUE THREAD

**Issue by zazuwa** [padams/Open-Web-Analytics#396]
개발자님, 안녕하세요 o_0
좋은 프로그램을 배포해주셔서, 아주 잘 사용하고 있습니다 ^^
사용 중에, 조금 이상한 문제점을 발견하였습니다.
혹시 버그는 아닌지요?

Dear developer,Hello o_0
By distributing a good program, I use it very well ^^
During use, I found a strange problem.
Is not it a bug?

1. Demo & Examples 데모 주소로 이동합니다. (http://demo.openwebanalytics.com/)
Go to "Demo & Examples" demo address. 

![](https://i.imgur.com/rMdkIuM.jpg)

----------

2. Main Reporting Dashboard 로 이동합니다. (http://demo.openwebanalytics.com/owa)
Go to the "Main Reporting Dashboard". (http://demo.openwebanalytics.com/owa)

![](https://i.imgur.com/MFRY0c4.jpg)

![](https://i.imgur.com/zYqu3Qn.jpg)

----------

3. 좌측 매뉴에서 View Reports (http://demo.openwebanalytics.com/owa/index.php?owa_siteId=c9b7d12e322c7c360fb8f7c72ffe4c41&owa_period=last_seven_days&owa_do=base.reportDashboard)로 이동합니다.
In the left menu, go to "View Reports" (http://demo.openwebanalytics.com/owa/index.php?owa_siteId=c9b7d12e322c7c360fb8f7c72ffe4c41&owa_period=last_seven_days&owa_do=base.reportDashboard).

![](https://i.imgur.com/gYZ8yHX.jpg)

----------

4. Most Frequent Visitors 항목에서 임의 Visitor ID 를 클릭합니다.
Under" Most Frequent Visitors", click the random "Visitor ID".

![](https://i.imgur.com/mkFcbM3.jpg)

----------

5. Visitor History 페이지가 깨져서 보입니다.
The "Visitor History" page looks garbled.

![](https://i.imgur.com/VoPtUth.jpg)

----------

제가 사용 중인 로그분석기에서만 그런 줄 알았는데,
제작사의 데모주소에서도 같은 문제가 있습니다.
이 부분은 어떻게 수정해야 합니까?
바쁘신 시간이겠지만, 답변 좀 부탁드려요^^
감사합니다 ^^

I thought that was the only log analyzer I was using,
The demo address of the manufacturer also has the same problem.
How do I fix this?
It will be a busy time, but please answer me ^^
Thank you ^ ^

**Comment by bennet-esyoil** [comment]
Hi, I'm looking into this issue currently and will open a PR with a fix.

**Comment by Maaiins** [comment]
Related to #456

**Comment by padams** [comment]
The visitor report got broken in all sorts of ways when we switched over to the new tracking event processing pipeline. Some of this is just trivial template fixes. 

The bigger issues that we no longer have an easy way to view total visits for a particular visitor. This used to be a dimension in the visitor table (if you can believe that) but we stopped populating that as it required an update of the visitor object every session which created a slowly changing dimension and something we want to avoid.

However we still have this data as the trackers store the number of prior sessions/visits the owa_v cookie (using the 'nps' key). This value is stored as a dimension in all fact tables for all tracking events (page view, session, action etc.

For now I'm going to remove the KPI box at the top of the screen as it would require that we write a special reporting API to count visits by a special visitor_id. But I am going to add the data to the visit summary box so that you can just look at the last visit to see the total prior visits.
