### ISSUE TITLE
Seting time period for statistics

### ISSUE THREAD

**Issue by watza** [padams/Open-Web-Analytics#45]
Hello, 
I have OWA 1.5.4 installed on my server / domain. The problem is I can see statistics only from the last 7 days. 
How can I set  or display stats from one month or full year? What should I do, where to click etc. 
I can navigate, look for visitors, browsers etc, but only for LAST 7 days. 
Please help - how to change to time view?
Regards
Rafal

**Comment by padams** [comment]
Upper right corner of the report is the data picker. Just click on it to open.

--
Peter Adams

**Comment by watza** [comment]
Sorry, but there is nothing about date. Could you please look at the screen and be more specific? Where it is?
![owa_epolpedia](https://cloud.githubusercontent.com/assets/10398886/5643455/024658e8-9659-11e4-95c0-1f439cb520f2.jpg)

**Comment by padams** [comment]
uh, that is strange. it’s clearly missing for your screenshot. Now i see why you are confused.
Please check to see that you installed all the OWA files correctly and check that you do not have any javascript errors.
Also try loading the interface with another browser.

**Comment by watza** [comment]
Yes, many thanks S. :)
It worked on Chrome, but IE and Firefox is bugging. I have to update my browsers, but at least I know where are my stats :) Cheers.

**Comment by padams** [comment]
What version/OS of firefox was this happening in?

**Comment by dachande** [comment]
This issue has been closed, but it can still be experienced with the latest OWA version which is 1.5.7.

The Time Period Control works perfect on Chrome and Internet Explorer but it doesn't work on Firefox.
This has been testet on Linux (Firefox 41.0) and Windows (Firefox 40.0.3).

Looking at the Debug Toolbar I get a ```not wellformed``` error in ```modules/base/templates/filter_period.tpl```

```
<div class="timePeriodControlContainer">

	<table id="owa_reportPeriodLabelContainer" cellpadding="0" cellspacing="0">
		<TR>
			<TD class="owa_reportPeriodLabelText">
			
				<span>
					<*=this.datelabel *>
				</span>						
			</TD>
			
			<TD class="owa_reportRevealControl"></TD>	
		</TR>
	</table>
[...]
</div>
```
With ```<*=this.datelabel *>``` being highlighted.

There is also the following in the file ```modules/base/js/owa.reporting-combined.min.js```:
```
TypeError: h is undefined
```

**Comment by padams** [comment]
I can't reproduce this on firefox 44.0.2 running on OS X. If anyone else can please re-open.

**Comment by McNairy** [comment]
I had this issue (missing date picker) on a system I inherited with IIS 7.5 and OWA 1.5.7. using Chrome dev tools I saw that /services/owa/modules/base/templates/filter_period.tpl was not found. Since the file did in fact exist and had correct access permissions I checked to see if .tpl files were being processed by PHP. They weren't. I added a module mapping and reset the server and it worked.

**Comment by dac2020** [comment]
I know this is an old issue but I don't really want to open another one. 
On firefox 52, owa 1.6.0 works fine for me. 
However, there is another thing I'm a little confused about.
I've tried to set the data range, in my case, I want to see the entire year, from jan to dec but those settings keep getting lost so I have to re-set it over and over again.
Is there something I could configure which would leave this setting permanently?

**Comment by padams** [comment]
it should stick automatically. can you detail the steps and associated URLs to reproduce this?

**Comment by dac2020** [comment]
Associated URLs? If you mean post my site publicly here on github, I can't do that.

In terms of how I am trying to change the date, I'm clicking on the  date/time on the upper right hand corner to bring the drop down up.

I've tried selecting Predefined Periods but they never stay and I have to do it again if I move away from that site.
I've also picked a Date Range such as Jan 1/17 to current day.
In both cases, I then click on Change Date Range.

What I mean by moving away from that site is going back to Sites Roster, the setting is lost every time.

**Comment by padams** [comment]
We need the exact steps to reproduce. Sanitize the URLs.

**Comment by dac2020** [comment]
I'm not sure what to provide but any time I move away from the Dashboard of a site I want to see stats for, the date/time is reset for that site back to Last Seven Days.

There really isn't anything I can show to reproduce, it's as simple as that.
Maybe something is not getting written somewhere to keep the setting? Where could I look for this setting, in a file or in the db?

**Comment by padams** [comment]
It's not a setting. It's standard behavior of how the reporting works. 

Detail the exact steps describing exactly what you click on or select once you load the dashboard for the first time.

Also we need to sanitized urls of the pages.

**Comment by dac2020** [comment]
Let's see if I can provide what you're asking for.

Sites Roster
http://owa.domain.com/index.php?owa_do=base.sites 
Here I see the list of two sites, one wordpress, the other phpbb. At this point, the wp site is always showing only the last 7 days in the preview. 

The phpbb doesn't work yet so no idea how to get stats from it. As I understand it, I needed to add the tracking code in the  /styles/prosilver/template/overall_footer.php but that is not generating anything. 

Next I click on the wp reports
http://owa.domain.com/index.php?owa_do=base.reportDashboard&owa_siteId=xxx

The reports show the last seven days so I click on the date/time dropdown.
Can't really show you that since it doesn't change the URL.

I change the date to Jan 1/17 to current and click on Change Date Range.
Now I can see stats since Jan1 on all Dashboard pages.

As soon as I go back to Reporting or Sites Roster, the date is changed back to seven days again.

Is this what you want? I'm not sure what else to add?

**Comment by padams** [comment]
When you say "whenever you go back to reporting or sites roster" we need to know how are you going that. Are you using the browsers back button or exactly what are you clicking on and what is the resulting URL.

Sorry if this seems obvious but it's not and is essential to properly report and resolve bugs.

Anyone should be able to mechanically follow your steps to reproduce the bug otherwise it will never get fixed.

Thanks.

**Comment by dac2020** [comment]
It's fine, I'm happy to provide details. Just need to understand what you need :).

No, I'm not using the back button. I'm using the links at the top of the first page;
    Reporting    Administration    Help    Report a Bug

No matter how I get back to that site, the range goes back to seven days. Meaning, even if I click Administration, then Tracked Sites, it's always back to seven days.

**Comment by padams** [comment]
What happens when you set the date range and then navigate to another report listed in the left hand reports list?

**Comment by dac2020** [comment]
I tried that also. 

From the top page, Sites Roster (http://owa.domain.com/index.php?owa_do=base.sites)

I change the range to Jan 1/17 and the preview for wp shows since Jan. 
However, as soon as I go visit either sites reports, it changes back to seven days.

Any time I move away from the WP site/reports, it changes back to seven days.

**Comment by padams** [comment]
this is why URLs and steps matter. 

Are you talking about clicking on the link “view Reports” present in each row of the Sites Roster Page?

**Comment by padams** [comment]
Try the fix i just pushed.

**Comment by dac2020** [comment]
To confirm, it should look like this now;

`                                <td valign="" style="min-width:300px;">
                                        <span style="font-size:14px; font-weight:bold;">
                                                <a href="<?php echo $this->makeLink( array('do' => 'base.reportDashboard', 'siteId' => $site->get('site_id') ), false );?>"><?php $this->out( $site->get('name') );?></a>
                                        </span><BR>
                                        <?php if ($site->get('description') != ''):?>
                                        <span class="info_text"><?php $this->out( $site->get('description') );?></span><BR>
                                        <?php endif;?>
                                        <span class="externalUrl"><?php $this->out( $site->get('domain') );?></span><BR><BR>
                                        <div>
-                                       <a href="<?php echo $this->makeLink( array('do' => 'base.reportDashboard', 'siteId' => $site->get('site_id') ), false );?>">View Reports</a> |
+                                       <a href="<?php echo $this->makeLink( array('do' => 'base.reportDashboard', 'siteId' => $site->get('site_id') ), true );?>">View Reports</a> |
                                        <a href="<?php echo $this->makeLink( array('do' => 'base.sitesProfile', 'siteId' => $site->get('site_id'), 'edit' => true ) );?>">Edit Profile</a> |
                                        <a href="<?php echo $this->makeLink( array('do' => 'base.sitesInvocation', 'siteId' => $site->get('site_id') ) );?>">Get Tracking Code</a> |
                                        <a href="<?php echo $this->makeLink( array('do' => 'base.optionsGoals', 'siteId' => $site->get('site_id') ) );?>">Goals</a>
                                        |
                                        <a href="<?php echo $this->makeLink( array('do' => 'base.sitesDelete', 'siteId' => $site->get('site_id') ), false, false, false, true );?>">Delete</a>
                                        </div>
                                </td>
`

**Comment by padams** [comment]
No. when you see a diff on GitHub the lines in red are removed and the lines in green are new. You added both. See the diff above.

**Comment by dac2020** [comment]
Only the following then.

<?php endif;?>
<span class="externalUrl">

Believe it or not, it's already exactly this.

<?php endif;?>
<span class="externalUrl">

Maybe I'm not seeing a stubble difference.

**Comment by padams** [comment]
post that file here as an attachment.

**Comment by dac2020** [comment]
[sites.zip](https://github.com/padams/Open-Web-Analytics/files/900327/sites.zip)

**Comment by padams** [comment]
[sites.tpl.zip](https://github.com/padams/Open-Web-Analytics/files/901431/sites.tpl.zip)

here is the change.

**Comment by dac2020** [comment]
Thanks. I hate to say it but the data still changes back to the last 7 days. 

I tried to gather up more info for you but it's acting all random and too hard to keep track of all the weird things that are happening. 

From the Reporting (main view) page, 
http://owa.domain.com/index.php?owa_do=base.sites
I try to change the range to This Year
which shows the year of data but as soon as I go into the WP reports
http://owa.domain.com/index.php?owa_do=base.reportDashboard&owa_siteId=xxx
...it shows only the last 7 days again.

I go back to Reporting and it's back to 7 days again.
I change it back to This Year and this time I click on the WP View Reports option rather than the title link
http://owa.domain.com/index.php?owa_siteId=xxx&owa_period=this_year&owa_do=base.reportDashboard

This time it shows the year of data.
I go back to Reporting and it's back to 7 days again.

**Comment by Phoenix90210** [comment]
Hi All,
I'm using version 1.6.0 based on windows and found that the time filter did not appear at all on the application after install.
I verified that the filter_period.tpl was indeed in the right place with the right permissions in *owa_dir*/modules/templates/

Using Firebug I identified that there was a 404 error when trying to open the file.
Navigation to the folder through IIS and then browsing the location produced a 404.3 error which was far more helpful.

Solution:

1. At the site level in IIS in the feature menu click on MIME Types
2. In the top Right click Add...
3. Add the following Extension and MIME type
Extension:        *.tpl
MIME Type:     application/vnd.groove-tool-template
4. Click OK
5. Run CMD then type in iisreset and hit Enter

You will now have the time filter module available for your use.

Hope people find this useful.

**Comment by dac2020** [comment]
So, you are thinking it's because the web server doesn't know about this type?
In Linux or using Apache, then someone would have to add something like this in the MIME type directives.

<IfModule mime_module>
        AddType application/vnd.groove-tool-template .tpl
</IfModule>

**Comment by mariomurrent-softwaresolutions** [comment]
> Sorry, but there is nothing about date. Could you please look at the screen and be more specific? Where it is?
> ![owa_epolpedia](https://cloud.githubusercontent.com/assets/10398886/5643455/024658e8-9659-11e4-95c0-1f439cb520f2.jpg)

Same for me. Installed on a webspace and I don't see any dropdown in any browser :(
