### ISSUE TITLE
other users to add your site

### ISSUE THREAD

**Issue by sonic69** [padams/Open-Web-Analytics#59]
Hi 
I want other users to add your site in piwik! 
Can this be done?

**Comment by padams** [comment]
I'm not understanding your question.

**Comment by sonic69** [comment]
I apologize ....
I love every user can register on my site
And the user can add their sites to analyze the script (http://www.openwebanalytics.com/)
How can I do this work?

**Comment by sonic69** [comment]
please help me :(

**Comment by sonic69** [comment]
help me :)

**Comment by sonic69** [comment]
@padams help :(

**Comment by padams** [comment]
I really do not understood your question but here's an attempt at guessing what you are after....

You must have a User account in the OWAS Admin interface in order to generate javascript tracking code for use on a website. There is no self-serve way to give users OWA admin accounts that must be done by an existing admin via the GUI.
